### PR TITLE
Update dependences

### PR DESCRIPTION
**Pull request by krzy5iek**
Replace obsolete 'GeoRuby' gem with it's newer version 'georuby' to support ruby 2.2

### CODE REVIEW

**Comment by mathiasnordvang** [comment]
As the current version of thalamus imports this gem with `gem 'spatial_adapter', github: 'inviso-org/spatial_adapter'` I guess merging this PR will affect all new builds/deployments on thalamus/master. Maybe its worth committing in a locked version on thalamus/master before merging this? Or just keeping this as a separate branch until we're on ruby 2 in production. Unless @skalar-bcawkwell has another idea.

**Comment by skalar-bcawkwell** [comment]
Hopefully the gemfile.lock will ensure the current version is used, and we will not have to worry about this. Lets just do a double check after its merged that the old version still gets used by thalamus by pushing to experimental.

**Comment by skalar-bcawkwell** [comment]
@krzy5iek Could you provide a brief reason in the description why it needs to be updated, eg. Ruby version support, if that is the reason.

**Comment by krzy5iek** [comment]
I added description.

**Review by skalar-bcawkwell — APPROVED** [review]

**Pull request merged**
